[package]
name = "zq_iterator"
version = "0.1.0"
edition = "2021"
license="MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
opt-level=0

[profile.release]
op-level=3
